name       : gnutls
version    : 3.3.14
release    : 1
source     :
    - http://ftp.heanet.ie/mirrors/ftp.gnupg.org/gcrypt/gnutls/v3.3/gnutls-3.3.14.tar.xz : 0dfa0030faad8909c1e904105198232d6bc0123cae8cf4933b2bac85ee7cec52
license    : LGPL-2.0+
summary    : The GnuTLS package contains libraries and userspace tools which provide a secure layer over a reliable transport layer.
clang      : no
description: |
    The GnuTLS package contains libraries and userspace tools which provide a secure layer over a reliable transport layer.
builddeps  :
    - pkgconfig(nettle)
    - pkgconfig(autoopts)
    - pkgconfig(p11-kit-1)
    - pkgconfig(libtasn1)
setup      : |
    %configure --disable-static --with-default-trust-store-file=/etc/ssl/ca-certificates.crt
build      : |
    %make -j1
install    : |
    %make_install
