name        : vala
version     : 0.27.2
release     : 10
source      :
    - http://ftp.gnome.org/pub/gnome/sources/vala/0.27/vala-0.27.2.tar.xz : 80e87d312cad0185691c4973b2e46fd15ab5557e818b319d3955cca0360b6453
homepage    : https://live.gnome.org/Vala
license     :
    - GPLv3+
summary     : Compiler for the GObject type system
description : |
    Vala is a new programming language that aims to bring modern programming language features to GNOME developers without imposing any additional runtime requirements and without using a different ABI compared to applications and libraries written in C.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
