name       : atom
version    : 0.194.0
release    : 1
source     :
    - https://github.com/atom/atom/archive/v0.194.0.tar.gz : a858c4a838e084c5ef067eccad14b15cb858e7b542f892c0a9a2e45bbb678741
license    : GitHub Copyright
summary    : Atom is a hackable text editor for the 21st century.
description: |
   Atom is a hackable text editor for the 21st century.
clang  :  no
builddeps  : git nodejs nodejs-devel libgnome-keyring libgnome-keyring-devel
    gcc g++ sed
build      : |
    export DESCRIPTION="Atom is a hackable text editor for the 21st century."

    mkdir -p %installroot%/usr/share/applications
    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build

    sed -e "s/<%= description %>/$DESCRIPTION/"  -e "s|<%= executable %>|/usr/bin/atom|"  -e "s|<%= iconName %>|atom|" resources/linux/atom.desktop.in > resources/linux/Atom.desktop

    install -Dm644 resources/linux/Atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/atom.png %installroot%/usr/share/pixmaps/atom.png
