name       : zopfli
version    : 1.0
release    : 1
source     :
    - https://github.com/google/zopfli/archive/zopfli-1.0.0.tar.gz : 386bd801e99bd95f292e7c39fa6a945e4bf1ffec57e16a99024d766fdafb6f96
license    : APACHE 2
summary    : Zopfli Compression Algorithm is a compression library. 
description: |
    Zopfli Compression Algorithm is a compression library programmed in C to perform very good, but slow, deflate or zlib compression.
builddeps  : gcc glibc-devel
build      : |
    %make
install    : |
    mkdir -p %installroot%/usr/bin
    mv zopfli %installroot%/usr/bin/
