name       : gnome-calendar
version    : 3.16.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-calendar/3.16/gnome-calendar-3.16.1.tar.xz : 1db810f820dfc56fce0fb33f5add6d7946a0f8c803764fe9e572c68758f65caa
license    : GPL-2.0
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(libecal-1.2)
    - pkgconfig(libical)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
