name       : evopop-gtk-theme
version    : 0.22
release    : 2
source     :
    - https://github.com/poltertec/evopop-gtk-theme/releases/download/0.22/evopop-gtk-theme-0.22.tar.xz : afb26f4b74689e6cfc36c19cc5424fa88a93ec1b669adeb164ce80b4729c52b5
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Evolve OS & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Evolve OS & Budgie Desktop. Iris Dark was used as base.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
