name       : evopop-gtk-theme
version    : 0.24
release    : 4
source     :
    - https://github.com/solus-project/evopop-gtk-theme/releases/download/0.24/evopop-gtk-theme-0.24.tar.xz : cee7915df191181aa9146b89214edaa0579558243a454e2f41da83fc07a99f8d
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Evolve OS & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Evolve OS & Budgie Desktop. Iris Dark was used as base.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
