name       : libchardet
version    : 1.0.4
release    : 1
source     :
    - http://ftp.oops.org/pub/oops/libchardet/libchardet-1.0.4.tar.bz2 : f43f5a63901f19780b5cd61ad130d432a9414e2e4da2abc0e1b80845895a7c33
license    : GPL-2.0 # CHECK ME
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
