name       : baobab
version    : 3.16.0
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/baobab/3.16/baobab-3.16.0.tar.xz : db29c48892c36ea04f4f74019a24004c2fa54854a08f2d0be55f17d39ee9bf5c
license    : GPL-2
builddeps  :
    - itstool
    - pkgconfig(gtk+-3.0)
summary    : A graphical directory tree analyzer
description: |
    A graphical directory tree analyzer
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
