name       : evopop-icon-theme
version    : 0.4
release    : 3
source     :
    - https://github.com/solus-project/evopop-icon-theme/releases/download/0.4/EvoPop-0.4.tar.xz : f2849ba6218ae2bb7651968b917c785ba1486deeb05bdc8074c8f8e7c392963e
license    : CC-BY-4.0
summary    : EvoPop Icon Theme
description: |
    A simple icon theme with some google material design inspiration.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
