name       : gstreamer-editing-services
version    : 1.4.0
release    : 1
source     :
    - http://gstreamer.freedesktop.org/src/gst-editing-services/gstreamer-editing-services-1.4.0.tar.xz : cc20b90fb7bcec257b2afda7474664d493b1acece66da675d7df584588808bb3
license    : GPL-2.0 # CHECK ME
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libxml-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
