name        : gtksourceview
version     : 3.16.0
release     : 8
source      :
    - http://ftp.gnome.org/pub/gnome/sources/gtksourceview/3.16/gtksourceview-3.16.0.tar.xz : 4d9ae25d9b65ba02509fb42798e7b483b95b209ee640228b8613eea3271b0d19
homepage    : http://projects.gnome.org/gtksourceview/
license     :
    - GPLv2+
summary     : Syntax highlighting text editing C library
builddeps   :
    - pkgconfig(gtk+-3.0)
description : |
    GtkSourceView is a portable C library that extends the standard GTK+ framework for multiline text editing with support for configurable syntax highlighting, unlimited undo/redo, UTF-8 compliant caseless searching, printing and other features typical of a source code editor.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
