name        : rhythmbox
version     : 3.2
release     : 6
source      :
    - http://ftp.gnome.org/pub/GNOME/sources/rhythmbox/3.2/rhythmbox-3.2.tar.xz : 9c8adf79e4b2bb76cee391c73ba7a1e699e7684e5f45507e7d6849957ac54f81
homepage    : https://wiki.gnome.org/Apps/Rhythmbox
license     :
    - GPL-2.0
summary     : Music playing application for GNOME
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-gnome-2.4)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(tdb)
    - pkgconfig(totem-plparser)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(libnotify)
    - pkgconfig(clutter-1.0)
    - pkgconfig(pygobject-3.0)
    - itstool
    - vala
rundeps     :
    - python3-gobject
description : |
    Music playing application for GNOME
setup      : |
    %configure --disable-static \
               --enable-python \
               --enable-libnotify
build      : |
    %make
install    : |
    %make_install
