name       : gnome-bluetooth
version    : 3.16.0
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.16/gnome-bluetooth-3.16.0.tar.xz : fff7e5a608995c9ff5f69ae6113f05461470acd32a85b59016fdedeef791d3d8
license    : GPL, LGPL
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-3.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
